title: 梁靖松的个人主页
page-top-title: 梁靖松
top-section-bg-text: 计算机科学与技术 & 软件工程
home-subtitle: 梁靖松
copyright-text: '&copy; Github Open Source'

title_english: Jingsong Liang's Homepage
page-top-title_english: Jingsong Liang
top-section-bg-text_english: Computer Science & Software Engineering
home-subtitle_english: Jingsong Liang
copyright-text_english: '&copy; Github Open Source'

